### ISSUE TITLE
Appropiate qualificiation metrics

### ISSUE THREAD

**Issue by fretchen** [GFA-DIU/OpenSource4Impact#27]
Traditional tenders focus a lot on long time experience and company turnovers as metrics to find suitable companies. However, within the context of software projects this might not be the most suited metric. But what are more suited metrics ? Some clear requirements are:

1. It should be very likely that the company exists for the duration of the project. 
2. It should be likely that the company has the appropiate talent for the duration of the project. 

So if the project takes four years it is unlikely that a startup which exists since five months is a really wise choice. Can we formulate suited metrics for different kind of projects, I would guess that there are **small** (less than six months), **middle** (up to a year) and **big** (four years).

**Comment by gelicko** [comment]
1. very difficult to assess in the software business. I guess the best is still turnover and year of creation (maybe not amount of turnover, but rather stability). Generally: if you look at a specific (SaaS) solution provider, then there is a high risk if it is a startup. If you look at a classical IT service provider / individualized development company, then the difference to a classical tender is minimal.
2. to assess that, you need to know exactly what talent you need, i.e. which technology stack, which roles, etc. 
If you don't know that yet, then you don't know what you ask for. 
My experience is: for large projects, you want to ensure that you get a few key brains (domain expert, IT architect, etc.) and you don't need to worry so much about the rest (it can be outsourced and the key brains can do that no matter if the company itself is small). 
For smaller projects, you only have these key brains and they do everything

**Comment by fretchen** [comment]
It feels that a nice first step has been taken in [4cb5321](https://github.com/GFA-DIU/OpenSource4Impact/commit/4cb5321ada7efbbac4396a6e2241695997bb33e8). So I am fine to close this.
